In [1]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sb

In [16]:
class Model(nn.Module):
    def __init__(self,num_features):
      super().__init__()
      self.linear = nn.Linear(num_features,1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear(features)
      out = self.sigmoid(out)
      return out




In [17]:
# create dataset
features=torch.rand(10,5)
# create model
model= Model(features.shape[1])
# call model for forward pass
# model.forward(features)
model(features)

tensor([[0.5240],
        [0.6073],
        [0.5297],
        [0.5934],
        [0.5411],
        [0.5958],
        [0.6272],
        [0.4972],
        [0.5935],
        [0.5465]], grad_fn=<SigmoidBackward0>)

In [6]:
# show model weights
model.linear.weight


Parameter containing:
tensor([[-0.0192,  0.0302, -0.2261,  0.3198,  0.1471]], requires_grad=True)

In [7]:
# show model bias
model.linear.bias

Parameter containing:
tensor([-0.4069], requires_grad=True)

In [8]:
!pip install torchinfo

In [9]:
from torchinfo import summary
summary(model, input_size=(10,5))

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 1]                   6
├─Sigmoid: 1-2                           [10, 1]                   --
Total params: 6
Trainable params: 6
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [18]:
class Model(nn.Module):
    def __init__(self,num_features):
      super().__init__()
      self.linear1 = nn.Linear(num_features,3)
      self.relu=nn.ReLU()
      self.linear2 = nn.Linear(3,1)
      self.sigmoid = nn.Sigmoid()

    def forward(self, features):
      out = self.linear1(features)
      out = self.relu(out)
      out = self.linear2(out)
      out = self.sigmoid(out)
      return out




In [19]:
# create dataset
features=torch.rand(10,5)
# create model
model= Model(features.shape[1])
# call model for forward pass
# model.forward(features) , automatically without calling forward pass, it calls forward pass function
model(features) # called magic function

tensor([[0.6035],
        [0.6029],
        [0.6008],
        [0.6060],
        [0.6060],
        [0.6060],
        [0.6060],
        [0.6060],
        [0.6060],
        [0.6060]], grad_fn=<SigmoidBackward0>)

In [20]:
model.linear1.weight

Parameter containing:
tensor([[-0.2855, -0.3612,  0.1685,  0.0956, -0.3997],
        [-0.2559, -0.2612,  0.0183,  0.4384, -0.3153],
        [ 0.2299,  0.3661, -0.1500,  0.1753, -0.3981]], requires_grad=True)

In [21]:
model.linear2.weight

Parameter containing:
tensor([[-0.5146, -0.2442,  0.1425]], requires_grad=True)

In [22]:
summary(model, input_size=(10,5)  )

Layer (type:depth-idx)                   Output Shape              Param #
Model                                    [10, 1]                   --
├─Linear: 1-1                            [10, 3]                   18
├─ReLU: 1-2                              [10, 3]                   --
├─Linear: 1-3                            [10, 1]                   4
├─Sigmoid: 1-4                           [10, 1]                   --
Total params: 22
Trainable params: 22
Non-trainable params: 0
Total mult-adds (Units.MEGABYTES): 0.00
Input size (MB): 0.00
Forward/backward pass size (MB): 0.00
Params size (MB): 0.00
Estimated Total Size (MB): 0.00

In [23]:
# sequential containers
class Model(nn.Module):
    def __init__(self,num_features):
      super().__init__()
      self.network = nn.Sequential(
          nn.Linear(num_features,3),
          nn.ReLU(),
          nn.Linear(3,1),
          nn.Sigmoid()
      )


    def forward(self, features):
      out = self.network(features)
      return out





In [24]:
# create dataset
features=torch.rand(10,5)
# create model
model= Model(features.shape[1])
# call model for forward pass
# model.forward(features) , automatically without calling forward pass, it calls forward pass function
model(features) # called magic function

tensor([[0.4497],
        [0.4672],
        [0.4216],
        [0.4533],
        [0.4579],
        [0.4429],
        [0.4611],
        [0.4436],
        [0.4542],
        [0.4539]], grad_fn=<SigmoidBackward0>)