In [16]:
import pandas as pd
import numpy as np
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.preprocessing import LabelEncoder


In [2]:
df = pd.read_csv("https://raw.githubusercontent.com/gscdit/Breast-Cancer-Detection/refs/heads/master/data.csv")

In [3]:
df.head()

,id,diagnosis,radius_mean,texture_mean,perimeter_mean,area_mean,smoothness_mean,compactness_mean,concavity_mean,concave points_mean,...,texture_worst,perimeter_worst,area_worst,smoothness_worst,compactness_worst,concavity_worst,concave points_worst,symmetry_worst,fractal_dimension_worst,Unnamed: 32
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890,NaN
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902,NaN
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758,NaN
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300,NaN
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678,NaN


In [4]:
df.shape

(569, 33)

In [5]:
df.drop(columns=["id","Unnamed: 32"],inplace=True)

In [6]:
x_train,x_test,y_train,y_test = train_test_split(df.iloc[:,1:],df.iloc[:,0],test_size=0.2,random_state=42)

In [7]:
scaler=StandardScaler()
x_train=scaler.fit_transform(x_train)
x_test=scaler.transform(x_test)

In [8]:
x_train

array([[-1.44075296, -0.43531947, -1.36208497, ...,  0.9320124 ,
         2.09724217,  1.88645014],
       [ 1.97409619,  1.73302577,  2.09167167, ...,  2.6989469 ,
         1.89116053,  2.49783848],
       [-1.39998202, -1.24962228, -1.34520926, ..., -0.97023893,
         0.59760192,  0.0578942 ],
       ...,
       [ 0.04880192, -0.55500086, -0.06512547, ..., -1.23903365,
        -0.70863864, -1.27145475],
       [-0.03896885,  0.10207345, -0.03137406, ...,  1.05001236,
         0.43432185,  1.21336207],
       [-0.54860557,  0.31327591, -0.60350155, ..., -0.61102866,
        -0.3345212 , -0.84628745]])

In [9]:
y_train

,diagnosis
68,B
181,M
63,B
248,B
60,B
...,...
71,B
106,B
270,B
435,M


In [10]:
encoder=LabelEncoder()
y_train=encoder.fit_transform(y_train)
y_test=encoder.transform(y_test)

#NUMPY ARRAYS TO TENSORS FOR PYTORCH


In [11]:
x_train_tensor=torch.from_numpy(x_train)
x_test_tensor=torch.from_numpy(x_test)
y_train_tensor=torch.from_numpy(y_train)
y_test_tensor=torch.from_numpy(y_test)

In [12]:
x_train_tensor

tensor([[-1.4408, -0.4353, -1.3621,  ...,  0.9320,  2.0972,  1.8865],
        [ 1.9741,  1.7330,  2.0917,  ...,  2.6989,  1.8912,  2.4978],
        [-1.4000, -1.2496, -1.3452,  ..., -0.9702,  0.5976,  0.0579],
        ...,
        [ 0.0488, -0.5550, -0.0651,  ..., -1.2390, -0.7086, -1.2715],
        [-0.0390,  0.1021, -0.0314,  ...,  1.0500,  0.4343,  1.2134],
        [-0.5486,  0.3133, -0.6035,  ..., -0.6110, -0.3345, -0.8463]],
       dtype=torch.float64)

In [16]:
# DEFINING MODEL

In [33]:
class MySimpleNN():
  def __init__(self,x):
    self.weights=torch.rand(x.shape[1],1,dtype=torch.float64,requires_grad=True)
    self.bias=torch.zeros(1,dtype=torch.float64,requires_grad=True)
  def forward(self,x):
    z=torch.matmul(x,self.weights)+self.bias
    y_pred=torch.sigmoid(z)
    return y_pred
  def loss_function(self,y_pred,y):
    epsilon = 1e-7
    y_pred = torch.clamp(y_pred, epsilon, 1 - epsilon)
    loss = -(y_train_tensor * torch.log(y_pred) + (1 - y_train_tensor) * torch.log(1 - y_pred))
    loss = loss.mean()
    return loss


##TRAINING PIPELINE

In [49]:
#create model
model=MySimpleNN(x_train_tensor)
model.weights

tensor([[0.6043],
        [0.8860],
        [0.2671],
        [0.7519],
        [0.7506],
        [0.6611],
        [0.6513],
        [0.8285],
        [0.6324],
        [0.7471],
        [0.0924],
        [0.9616],
        [0.0330],
        [0.8994],
        [0.0535],
        [0.4864],
        [0.3340],
        [0.8486],
        [0.0046],
        [0.0922],
        [0.6653],
        [0.8483],
        [0.5527],
        [0.9022],
        [0.7074],
        [0.0551],
        [0.3013],
        [0.3525],
        [0.9885],
        [0.8070]], dtype=torch.float64, requires_grad=True)

In [26]:
model.bias

tensor([0.], dtype=torch.float64, requires_grad=True)

In [124]:
learning_rate=0.01
epochs=1000
model=MySimpleNN(x_train_tensor)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model.forward(x_train_tensor)

  # loss calculate
  loss=model.loss_function(y_pred,y_train_tensor)

  #backward pass
  loss.backward()

  #parameters update
  with torch.no_grad():
    model.weights-=learning_rate*model.weights.grad.data
    model.bias-=learning_rate*model.bias.grad.data

  #zero gradients
  model.weights.grad.zero_()
  model.bias.grad.zero_()

  #print loss in each epoch
  print(f"epoch {epoch+1} loss {loss.item()}")

epoch 1 loss 3.8072940018384767
epoch 2 loss 3.796092761574542
epoch 3 loss 3.784902459680437
epoch 4 loss 3.773723182626652
epoch 5 loss 3.762555018307547
epoch 6 loss 3.751398056046963
epoch 7 loss 3.7402523865978883
epoch 8 loss 3.7291181021524884
epoch 9 loss 3.7179952963508494
epoch 10 loss 3.7068420276528027
epoch 11 loss 3.6953439638534653
epoch 12 loss 3.6838582845944114
epoch 13 loss 3.6723560047830826
epoch 14 loss 3.660655921050254
epoch 15 loss 3.648907396141407
epoch 16 loss 3.6371721001238315
epoch 17 loss 3.625450151555698
epoch 18 loss 3.613741670684645
epoch 19 loss 3.6020284730239323
epoch 20 loss 3.59025419828576
epoch 21 loss 3.5784938172113834
epoch 22 loss 3.5667474581781713
epoch 23 loss 3.554952855176555
epoch 24 loss 3.543054326937611
epoch 25 loss 3.5311705033123033
epoch 26 loss 3.5193015231728677
epoch 27 loss 3.507447527189424
epoch 28 loss 3.4956086577808767
epoch 29 loss 3.4837097298807604
epoch 30 loss 3.4716705738027946
epoch 31 loss 3.4596290936906153


In [59]:
model.bias

tensor([0.0013], dtype=torch.float64, requires_grad=True)

In [125]:
# model evaluate
with torch.no_grad():
  y_pred=model.forward(x_test_tensor)

  y_pred=(y_pred>1).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy {accuracy}")



accuracy 0.6228070259094238


In [101]:
y_pred

tensor([[1.7841e-01],
        [9.7867e-01],
        [9.3381e-01],
        [3.5382e-01],
        [6.2453e-02],
        [1.0000e+00],
        [1.0000e+00],
        [9.5964e-01],
        [9.8913e-01],
        [7.6136e-05],
        [2.4115e-04],
        [8.4301e-01],
        [6.5707e-05],
        [9.9822e-01],
        [1.8288e-04],
        [1.0000e+00],
        [2.2016e-04],
        [3.4373e-04],
        [3.9395e-04],
        [9.9997e-01],
        [3.0356e-01],
        [8.6200e-03],
        [1.0000e+00],
        [6.4236e-06],
        [5.0933e-04],
        [5.2850e-01],
        [1.0823e-03],
        [1.9788e-02],
        [1.6026e-03],
        [1.0000e+00],
        [7.9707e-03],
        [7.9742e-05],
        [1.4450e-01],
        [4.0849e-04],
        [3.2169e-03],
        [1.7737e-03],
        [2.9186e-02],
        [2.1233e-03],
        [9.8329e-01],
        [4.9610e-03],
        [2.4465e-03],
        [9.9799e-01],
        [1.2196e-02],
        [4.2942e-04],
        [1.0306e-01],
        [1

In [99]:
(y_pred>0.9).float()

tensor([[0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
      

In [73]:
(y_pred==y_test_tensor).float()

tensor([[1., 0., 0.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 0., 0., 1.],
        [0., 1., 1.,  ..., 0., 0., 1.],
        ...,
        [1., 0., 0.,  ..., 1., 1., 0.],
        [1., 0., 0.,  ..., 1., 1., 0.],
        [0., 1., 1.,  ..., 0., 0., 1.]])

In [36]:
class MySimpleNN(nn.Module):
  def __init__(self,input_size):
    super().__init__()
    self.linear = nn.Linear(input_size,1)
    self.sigmoid = nn.Sigmoid()

  def forward(self,x):
    out = self.linear(x)
    out = self.sigmoid(out)
    return out



In [37]:
# define loss function
loss_function= nn.BCELoss()

In [30]:
y_train_tensor.reshape(-1,1).float()

tensor([[0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [1.],
        [0.],
        [1.],
        [1.],
        [1.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [0.],
        [1.],
        [1.],
      

In [38]:
learning_rate=0.01
epochs=1000
model=MySimpleNN(x_train_tensor.shape[1])
# define optimizer
optimizer = torch.optim.SGD(model.parameters(),lr=learning_rate)
#define loop
for epoch in range(epochs):
  #forward pass
  y_pred=model(x_train_tensor.float())# no need to call model.forward(), just call model(), forward function will call automatically due to magic function
  # loss calculate
  loss=loss_function(y_pred,y_train_tensor.view(-1,1).float())#.view() fucntion is similar to .reshape()

  # clear gradients
  optimizer.zero_grad()

  #backward pass
  loss.backward()

  #parameters update
  optimizer.step()

  #zero gradients
  model.linear.weight.grad.zero_()
  model.linear.bias.grad.zero_()

  #print loss in each epoch
  print(f"epoch {epoch+1} loss {loss.item()}")

epoch 1 loss 0.8895871043205261
epoch 2 loss 0.8596075773239136
epoch 3 loss 0.8312550187110901
epoch 4 loss 0.8044849634170532
epoch 5 loss 0.7792441844940186
epoch 6 loss 0.7554711699485779
epoch 7 loss 0.7330985069274902
epoch 8 loss 0.7120538353919983
epoch 9 loss 0.6922624707221985
epoch 10 loss 0.6736487150192261
epoch 11 loss 0.6561375856399536
epoch 12 loss 0.6396557688713074
epoch 13 loss 0.6241327524185181
epoch 14 loss 0.6095014214515686
epoch 15 loss 0.5956981778144836
epoch 16 loss 0.5826634764671326
epoch 17 loss 0.5703417658805847
epoch 18 loss 0.5586812496185303
epoch 19 loss 0.5476341247558594
epoch 20 loss 0.5371562242507935
epoch 21 loss 0.5272067189216614
epoch 22 loss 0.5177482962608337
epoch 23 loss 0.5087463855743408
epoch 24 loss 0.500169575214386
epoch 25 loss 0.49198856949806213
epoch 26 loss 0.4841769337654114
epoch 27 loss 0.4767100214958191
epoch 28 loss 0.4695654511451721
epoch 29 loss 0.4627225399017334
epoch 30 loss 0.4561622440814972
epoch 31 loss 0.449

In [39]:
# model evaluate
with torch.no_grad():
  y_pred=model.forward(x_test_tensor.float())

  y_pred=(y_pred>1).float()
  accuracy=(y_pred==y_test_tensor).float().mean()
  print(f"accuracy {accuracy}")



accuracy 0.6228070259094238
