# 📘 Tensors in Deep Learning (with PyTorch)

## 1. What is a Tensor?
A **tensor** is a specialized multi-dimensional array designed for mathematical and computational efficiency. Think of it as a generalization of scalars, vectors, and matrices to higher dimensions. Tensors are the basic data structure in PyTorch (and other deep learning frameworks).

---

## 2. Types of Tensors with Real-World Examples

| Tensor Type | Dimensions | Shape Example         | Real-World Example                       |
|-------------|------------|----------------------|------------------------------------------|
| Scalar      | 0D         | ()                   | Loss value (e.g., 5.0, -3.14)            |
| Vector      | 1D         | (n,)                 | Word embedding [0.12, -0.84, 0.33]       |
| Matrix      | 2D         | (m, n)               | Grayscale image [[0,255,128],[34,90,180]] |
| 3D Tensor   | 3D         | (w, h, c)            | RGB image (e.g., 256×256×3)              |
| 4D Tensor   | 4D         | (batch, w, h, c)     | Batch of 32 RGB images: [32,128,128,3]   |
| 5D Tensor   | 5D         | (batch, t, w, h, c)  | Video clips: [10,16,64,64,3]             |

### Examples
- **Scalars (0D):** Single value, e.g., loss = 5.0
- **Vectors (1D):** Feature vector, e.g., [0.12, -0.84, 0.33]
- **Matrices (2D):** Grayscale image, e.g.,
  ```
  [[0, 255, 128],
   [34,  90, 180]]
  ```
- **3D Tensors:** RGB image, shape [256, 256, 3]
- **4D Tensors:** Batch of 32 RGB images, shape [32, 128, 128, 3]
- **5D Tensors:** Batch of 10 video clips, each with 16 frames of size 64×64 (RGB): [10, 16, 64, 64, 3]

---

## 3. Why Are Tensors Useful?

- **Mathematical Operations:**
  - Enable fast operations: addition, multiplication, dot product, etc.
  - Essential for neural network computations.
- **Representation of Real-world Data:**
  - Images: 3D tensor (width × height × channels)
  - Text: Tokenized into 2D or 3D tensor (sequence length × embedding size)
  - Audio: 2D tensor (time × frequency)
  - Videos: 5D tensor (batch × frames × width × height × channels)
- **Efficient Computations:**
  - Optimized for GPUs/TPUs
  - Enable large-scale matrix multiplications crucial for training deep models

---

## 4. Where Are Tensors Used in Deep Learning?

- **Data Storage:**
  - Training data (images, text, audio, videos) stored as tensors
- **Weights & Biases:**
  - Neural network parameters (learnable values) are stored as tensors
  - Example: W (weights matrix), b (bias vector)
- **Matrix Operations in Neural Networks:**
  - Forward pass = matrix multiplications using tensors
  - Example:  
    $z = W \cdot x + b$  
    where W, x, and b are all tensors
- **Training Process:**
  - Forward pass: Tensors flow through the network to produce predictions
  - Backward pass: Gradients (also tensors) are computed using automatic differentiation

---

## 5. Summary (Quick Recall)

- **Scalars:** 0D (single value)
- **Vectors:** 1D (list of numbers)
- **Matrices:** 2D (tables)
- **3D+ Tensors:** Images, videos, batches
- **Tensors power deep learning:** Store data, model parameters, and enable fast GPU computations


In [ ]:
import torch
print(torch.__version__)

2.5.1+cu121


In [ ]:
if torch.cuda.is_available():
    print("GPU is available!")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("GPU not available. Using CPU.")

GPU is available!
Using GPU: Tesla T4


## Creating a Tensor

In [ ]:
# using empty
# Creates a tensor of shape (2, 3) with uninitialized values (whatever is in memory at that location).
# Useful for performance if you plan to fill the tensor with values right after creation.
a = torch.empty(2,3)

In [ ]:
# check type
# Returns the Python type of the variable 'a'.
# For a PyTorch tensor, this will be <class 'torch.Tensor'>.
type(a)

torch.Tensor

In [ ]:
# using zeros
# Creates a tensor of shape (2, 3) filled with zeros.
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [ ]:
# using ones
# Creates a tensor of shape (2, 3) filled with ones.
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
# using rand
# Creates a tensor of shape (2, 3) with random values uniformly sampled from [0, 1).
torch.rand(2,3)

tensor([[0.1192, 0.4828, 0.9105],
        [0.4266, 0.4203, 0.2719]])

In [ ]:
# use of seed
# Generates a tensor of shape (2, 3) with random values.
# Without setting a seed, the values will be different each time you run this cell.
torch.rand(2,3)

tensor([[0.0064, 0.4451, 0.1580],
        [0.8119, 0.4629, 0.3227]])

In [ ]:
# manual_seed
# Sets the seed for generating random numbers, so results are reproducible.
torch.manual_seed(100)
# Now, every time you run this, the random values will be the same.
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# manual_seed
# Setting the seed again ensures reproducibility for the next random operation.
torch.manual_seed(100)
# Generates the same random tensor as before due to the same seed.
torch.rand(2,3)

tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
# using tensor
# Creates a tensor directly from a nested Python list (2x3 matrix).
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# other ways

# arange
# Creates a 1D tensor with values from 0 to 8 (exclusive of 10), stepping by 2.
print("using arange ->", torch.arange(0,10,2))

# using linspace
# Creates a 1D tensor with 10 values evenly spaced between 0 and 10 (inclusive).
print("using linspace ->", torch.linspace(0,10,10))

# using eye
# Creates a 5x5 identity matrix (ones on the diagonal, zeros elsewhere).
print("using eye ->", torch.eye(5))

# using full
# Creates a 3x3 tensor filled with the value 5.
print("using full ->", torch.full((3, 3), 5))

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


## Tensor Shapes

In [ ]:
# Create a 2x3 tensor from a nested list
x = torch.tensor([[1,2,3],[4,5,6]])
# Display the tensor
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
# Get the shape of the tensor x
# Returns a torch.Size object representing the dimensions of x (here, (2, 3)).
x.shape

torch.Size([2, 3])

In [ ]:
# Create an empty tensor with the same shape as x
# The values are uninitialized (random in memory).
torch.empty_like(x)

tensor([[     134842408414608,       96429401449888,     3503044046096754],
        [-2738188572259385344,  7020378893157883663,  8389754676633367105]])

In [ ]:
# Create a tensor of zeros with the same shape as x
# All elements will be 0.
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
# Create a tensor of ones with the same shape as x
# All elements will be 1.
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
# Create a random tensor with the same shape as x
# The dtype is explicitly set to float32 (default for most deep learning tasks).
torch.rand_like(x, dtype=torch.float32)

tensor([[0.4076, 0.6037, 0.9820],
        [0.0117, 0.3891, 0.5056]])

## Tensor Data Types

In [ ]:
# find data type
x.dtype

torch.int64

In [ ]:
# assign data type
torch.tensor([1.0,2.0,3.0], dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
torch.tensor([1,2,3], dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [ ]:
# using to()
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

| **Data Type**             | **Dtype**         | **Description**                                                                                                                                                                |
|---------------------------|-------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **32-bit Floating Point** | `torch.float32`   | Standard floating-point type used for most deep learning tasks. Provides a balance between precision and memory usage.                                                         |
| **64-bit Floating Point** | `torch.float64`   | Double-precision floating point. Useful for high-precision numerical tasks but uses more memory.                                                                               |
| **16-bit Floating Point** | `torch.float16`   | Half-precision floating point. Commonly used in mixed-precision training to reduce memory and computational overhead on modern GPUs.                                            |
| **BFloat16**              | `torch.bfloat16`  | Brain floating-point format with reduced precision compared to `float16`. Used in mixed-precision training, especially on TPUs.                                                |
| **8-bit Floating Point**  | `torch.float8`    | Ultra-low-precision floating point. Used for experimental applications and extreme memory-constrained environments (less common).                                               |
| **8-bit Integer**         | `torch.int8`      | 8-bit signed integer. Used for quantized models to save memory and computation in inference.                                                                                   |
| **16-bit Integer**        | `torch.int16`     | 16-bit signed integer. Useful for special numerical tasks requiring intermediate precision.                                                                                    |
| **32-bit Integer**        | `torch.int32`     | Standard signed integer type. Commonly used for indexing and general-purpose numerical tasks.                                                                                  |
| **64-bit Integer**        | `torch.int64`     | Long integer type. Often used for large indexing arrays or for tasks involving large numbers.                                                                                  |
| **8-bit Unsigned Integer**| `torch.uint8`     | 8-bit unsigned integer. Commonly used for image data (e.g., pixel values between 0 and 255).                                                                                    |
| **Boolean**               | `torch.bool`      | Boolean type, stores `True` or `False` values. Often used for masks in logical operations.                                                                                      |
| **Complex 64**            | `torch.complex64` | Complex number type with 32-bit real and 32-bit imaginary parts. Used for scientific and signal processing tasks.                                                               |
| **Complex 128**           | `torch.complex128`| Complex number type with 64-bit real and 64-bit imaginary parts. Offers higher precision but uses more memory.                                                                 |
| **Quantized Integer**     | `torch.qint8`     | Quantized signed 8-bit integer. Used in quantized models for efficient inference.                                                                                              |
| **Quantized Unsigned Integer** | `torch.quint8` | Quantized unsigned 8-bit integer. Often used for quantized tensors in image-related tasks.                                                                                     |


## Mathematical operations

### 1. Scalar operation

In [ ]:
# Create a 2x2 tensor with random values between 0 and 1
x = torch.rand(2,2)
# Display the tensor
x

tensor([[0.9594, 0.1334],
        [0.8591, 0.6639]])

In [ ]:
# addition
# Adds 2 to every element in x
x + 2

# subtraction
# Subtracts 2 from every element in x
x - 2

# multiplication
# Multiplies every element in x by 3
x * 3

# division
# Divides every element in x by 3
x / 3

# integer division
# Multiplies x by 100, then performs integer division by 3 (drops decimals)
(x * 100)//3

# modulo
# Finds the remainder when each element (after integer division) is divided by 2
((x * 100)//3)%2

# power
# Squares every element in x (raises to the power of 2)
x**2

tensor([[0.9205, 0.0178],
        [0.7380, 0.4408]])

### 2. Element wise operation

In [ ]:
# Create two 2x3 tensors with random values between 0 and 1
a = torch.rand(2,3)
b = torch.rand(2,3)

# Print the tensors to see their values
print(a)
print(b)

tensor([[0.0554, 0.7498, 0.3761],
        [0.6721, 0.5572, 0.2686]])
tensor([[0.3466, 0.1875, 0.7433],
        [0.6713, 0.9844, 0.0096]])


In [ ]:
# add
# Adds corresponding elements of a and b
a + b

# sub
# Subtracts corresponding elements of b from a
a - b

# multiply
# Multiplies corresponding elements of a and b
a * b

# division
# Divides corresponding elements of a by b
a / b

# power
# Raises each element of a to the power of the corresponding element in b
a ** b

# mod
# Computes the remainder of each element in a divided by the corresponding element in b
a % b

tensor([[0.0554, 0.1872, 0.3761],
        [0.0008, 0.5572, 0.0091]])

In [ ]:
# Create a 1D tensor with both positive and negative values
c = torch.tensor([1, -2, 3, -4])

In [ ]:
# abs
# Returns a tensor with the absolute value of each element in c (removes negative sign)
torch.abs(c)

tensor([1, 2, 3, 4])

In [ ]:
# negative
# Returns a tensor with the sign of each element in c flipped (positive becomes negative and vice versa)
torch.neg(c)

tensor([-1,  2, -3,  4])

In [ ]:
# Create a 1D tensor with floating-point values
d = torch.tensor([1.9, 2.3, 3.7, 4.4])

In [ ]:
# round
# Rounds each element in d to the nearest integer
torch.round(d)

tensor([2., 2., 4., 4.])

In [ ]:
# ceil
# Rounds each element in d up to the nearest integer (ceiling)
torch.ceil(d)

tensor([2., 3., 4., 5.])

In [ ]:
# floor
# Rounds each element in d down to the nearest integer (floor)
torch.floor(d)

tensor([1., 2., 3., 4.])

In [ ]:
# clamp
# Restricts each element in d to be within the range [2, 3]
torch.clamp(d, min=2, max=3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### 3. Reduction operation

In [ ]:
# Create a 2x3 tensor with random float values between 0 and 10
# Used for demonstrating reduction operations (sum, mean, etc.)
e = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
e

tensor([[1., 2., 9.],
        [7., 6., 5.]])

In [ ]:
# sum
# Computes the sum of all elements in e
torch.sum(e)

# sum along columns (dim=0)
# Sums elements in each column, returns a 1D tensor with the sum for each column
torch.sum(e, dim=0)

# sum along rows (dim=1)
# Sums elements in each row, returns a 1D tensor with the sum for each row
torch.sum(e, dim=1)

tensor([18, 13])

In [ ]:
# mean
# Computes the mean (average) of all elements in e
torch.mean(e)

# mean along columns (dim=0)
# Computes the mean for each column
torch.mean(e, dim=0)

tensor([4., 4., 7.])

In [ ]:
# median
# Returns the median value of all elements in e (middle value when sorted)
torch.median(e)

tensor(5.)

In [ ]:
# max and min
# Returns the maximum value in e
torch.max(e)
# Returns the minimum value in e
torch.min(e)

tensor(1.)

In [ ]:
# product
# Returns the product of all elements in e (multiplies them together)
torch.prod(e)

tensor(3780.)

In [ ]:
# standard deviation
# Returns the standard deviation of all elements in e (measure of spread)
torch.std(e)

tensor(3.0332)

In [ ]:
# variance
# Returns the variance of all elements in e (measure of how far values spread from the mean)
torch.var(e)

tensor(9.2000)

In [ ]:
# argmax
# Returns the index of the maximum value in e (flattened tensor)
torch.argmax(e)

tensor(2)

In [ ]:
# argmin
# Returns the index of the minimum value in e (flattened tensor)
torch.argmin(e)

tensor(0)

### 4. Matrix operations

In [ ]:
# Create a 2x3 matrix (tensor) with random integers between 0 and 9
f = torch.randint(size=(2,3), low=0, high=10)
# Create a 3x2 matrix (tensor) with random integers between 0 and 9
g = torch.randint(size=(3,2), low=0, high=10)

# Print both matrices to see their values
print(f)
print(g)

tensor([[3, 7, 8],
        [7, 9, 9]])
tensor([[1, 1],
        [4, 2],
        [4, 7]])


In [ ]:
# matrix multiplication
# Multiplies matrix f (2x3) with matrix g (3x2) using matrix multiplication rules
# The result is a 2x2 matrix
torch.matmul(f, g)

tensor([[63, 73],
        [79, 88]])

In [ ]:
# Create two 1D tensors (vectors)
vector1 = torch.tensor([1, 2])
vector2 = torch.tensor([3, 4])

# dot product
# Computes the dot product of vector1 and vector2 (1*3 + 2*4 = 11)
torch.dot(vector1, vector2)

tensor(11)

In [ ]:
# transpose
# Swaps rows and columns of matrix f (2x3 becomes 3x2)
torch.transpose(f, 0, 1)

tensor([[3, 7],
        [7, 9],
        [8, 9]])

In [ ]:
# Create a 3x3 matrix (tensor) with random float values between 0 and 9
h = torch.randint(size=(3,3), low=0, high=10, dtype=torch.float32)
h

tensor([[8., 2., 2.],
        [4., 8., 8.],
        [5., 0., 4.]])

In [ ]:
# determinant
# Computes the determinant of matrix h (must be square)
torch.det(h)

tensor(224.)

In [ ]:
# inverse
# Computes the inverse of matrix h (must be square and non-singular)
torch.inverse(h)

tensor([[ 0.1429, -0.0357,  0.0000],
        [ 0.1071,  0.0982, -0.2500],
        [-0.1786,  0.0446,  0.2500]])

### 5. Comparison operations

In [ ]:
# Create two 2x3 tensors with random integers between 0 and 9
i = torch.randint(size=(2,3), low=0, high=10)
j = torch.randint(size=(2,3), low=0, high=10)

# Print both tensors to see their values
print(i)
print(j)

tensor([[5, 0, 1],
        [1, 1, 3]])
tensor([[2, 6, 3],
        [5, 2, 5]])


In [ ]:
# greater than
# Returns a boolean tensor where each element is True if i > j, else False
i > j

# less than
# Returns a boolean tensor where each element is True if i < j, else False
i < j

# equal to
# Returns a boolean tensor where each element is True if i == j, else False
i == j

# not equal to
# Returns a boolean tensor where each element is True if i != j, else False
i != j

# greater than or equal to
# Returns a boolean tensor where each element is True if i >= j, else False
i >= j

# less than or equal to
# Returns a boolean tensor where each element is True if i <= j, else False
i <= j

tensor([[True, True, True],
        [True, True, True]])

### 6. Special functions

In [ ]:
# Create a 2x3 tensor with random float values between 0 and 9
k = torch.randint(size=(2,3), low=0, high=10, dtype=torch.float32)
k

tensor([[0., 6., 4.],
        [4., 8., 6.]])

In [ ]:
# log
# Applies the natural logarithm to each element in k
torch.log(k)

tensor([[1.6094, 1.3863, 0.0000],
        [1.9459, 0.0000, 2.0794]])

In [ ]:
# exp
# Applies the exponential function (e^x) to each element in k
torch.exp(k)

tensor([[1.4841e+02, 5.4598e+01, 2.7183e+00],
        [1.0966e+03, 2.7183e+00, 2.9810e+03]])

In [ ]:
# sqrt
# Applies the square root to each element in k
torch.sqrt(k)

tensor([[2.2361, 2.0000, 1.0000],
        [2.6458, 1.0000, 2.8284]])

In [ ]:
# sigmoid
# Applies the sigmoid function to each element in k (output between 0 and 1)
torch.sigmoid(k)

tensor([[0.9933, 0.9820, 0.7311],
        [0.9991, 0.7311, 0.9997]])

In [ ]:
# softmax
# Applies the softmax function to k along dimension 0 (columns)
# Softmax converts values to probabilities that sum to 1 along the specified dimension
torch.softmax(k, dim=0)

tensor([[0.0180, 0.1192, 0.1192],
        [0.9820, 0.8808, 0.8808]])

In [ ]:
# relu
# Applies the ReLU (Rectified Linear Unit) function to each element in k
# ReLU sets all negative values to 0
torch.relu(k)

tensor([[0., 6., 4.],
        [4., 8., 6.]])

## Inplace Operations

In [ ]:
# Create two 2x3 tensors with random values between 0 and 1
m = torch.rand(2,3)
n = torch.rand(2,3)

# Print both tensors to see their values
print(m)
print(n)

tensor([[0.2018, 0.1089, 0.7653],
        [0.6473, 0.3401, 0.6406]])
tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])


In [ ]:
# In-place addition: adds n to m and stores the result in m
# The original m is modified (not a new tensor)
m.add_(n)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
# Display the modified tensor m after in-place addition
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
# Display the tensor n (unchanged)
n

tensor([[0.4749, 0.1632, 0.6222],
        [0.5379, 0.2758, 0.7180]])

In [ ]:
# Applies the ReLU function to m (not in-place)
# Returns a new tensor where all negative values in m are set to 0
torch.relu(m)

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
# In-place ReLU: sets all negative values in m to 0, modifying m directly
m.relu_()

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

In [ ]:
# Display the modified tensor m after in-place ReLU
m

tensor([[0.6767, 0.2721, 1.3875],
        [1.1851, 0.6159, 1.3585]])

## Copying a Tensor

In [ ]:
# Create a 2x3 tensor with random values between 0 and 1
a = torch.rand(2,3)
# Display the tensor a
a

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Assign a to b (no copy, just reference)
b = a

In [ ]:
# Display b (which is just a reference to a)
b

tensor([[0.5153, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Modify the first element of a (also changes b since b is just a reference)
a[0][0] = 0

In [ ]:
# Display a after modification
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Display b after modification of a (shows b is also changed)
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Check the memory id of a (shows both a and b point to the same object)
id(a)

134838567488544

In [ ]:
# Check the memory id of b (should be the same as a)
id(b)

134838567488544

In [ ]:
# Make a true copy of a using clone()
b = a.clone()

In [ ]:
# Display a after cloning (should be unchanged)
a

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Display b after cloning (should be a separate copy)
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Modify a after cloning (should not affect b)
a[0][0] = 10

In [ ]:
# Display a after modification (should show the change)
a

tensor([[10.0000,  0.9985,  0.6783],
        [ 0.2776,  0.6227,  0.2982]])

In [ ]:
# Display b after a is modified (should be unchanged if clone worked)
b

tensor([[0.0000, 0.9985, 0.6783],
        [0.2776, 0.6227, 0.2982]])

In [ ]:
# Check the memory id of a (should be different from b after clone)
id(a)

134838567488544

In [ ]:
# Check the memory id of b (should be different from a after clone)
id(b)

134838569581552